version: '3.8'
services:
  app:
    build: .
    environment:
      - DATADOG_API_KEY=${DATADOG_API_KEY}
      - DD_SERVICE=spring-datadog-demo
      - DD_ENV=dev
      - DD_VERSION=1.0.0
      - DD_AGENT_HOST=datadog
    ports:
      - "8080:8080"
    depends_on:
      - datadog

  datadog:
    image: datadog/agent:latest
    environment:
      - DD_API_KEY=${DATADOG_API_KEY}
      - DD_SITE=datadoghq.com
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_APM_ENABLED=true
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
    ports:
      - "8126:8126"   # Traces
      - "8125:8125/udp" # Metrics
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
